# Lavender
D_Levander_Sapling:
  name: $D_Levander
  growTime: 4000
  growRadius: 0.100000001
  minScale: 0.899999976
  maxScale: 1.10000002
  needCultivatedGround: true
  destroyIfCantGrow: false
D_Levander_Seed_Sapling:
  name: $D_Levander_Seeds
  growTime: 4000
  growRadius: 0.100000001
  minScale: 0.899999976
  maxScale: 1.10000002
  needCultivatedGround: true
  destroyIfCantGrow: false

# Dandelion
D_Dandelion_Sapling:
  name: $D_Dandelion
  growTime: 4000
  growRadius: 0.5
  minScale: 0.899999976
  maxScale: 1.10000002
  needCultivatedGround: true
  destroyIfCantGrow: false
D_QDandelion_Sapling:
  name: $D_Pickable_QDandelion
  growTime: 4000
  growRadius: 0.5
  minScale: 0.899999976
  maxScale: 1.10000002
  needCultivatedGround: true
  destroyIfCantGrow: false

# Rosemary
D_Rosemary_Sapling:
  name: $D_Rosemary
  growTime: 2000
  growRadius: 0.7
  minScale: 0.9
  maxScale: 1.1
  needCultivatedGround: true
  destroyIfCantGrow: false
D_Rosemary_Seed_Sapling:
  name: $D_Rosemary_Seeds
  growTime: 2000
  growRadius: 0.7
  minScale: 0.9
  maxScale: 1.1
  needCultivatedGround: true
  destroyIfCantGrow: false

# Chervil
D_Chervil_Sapling:
  name: $D_Chervil
  growTime: 2000
  growRadius: 0.7
  minScale: 0.9
  maxScale: 1.1
  needCultivatedGround: true
  destroyIfCantGrow: false
D_Chervil_Seed_Sapling:
  name: $D_Chervil_Seeds
  growTime: 2000
  growRadius: 0.7
  minScale: 0.9
  maxScale: 1.1
  needCultivatedGround: true
  destroyIfCantGrow: false

# Chives
D_Chives_Sapling:
  name: $D_Chives
  growTime: 2000
  growRadius: 0.7
  minScale: 0.9
  maxScale: 1.1
  needCultivatedGround: true
  destroyIfCantGrow: false
D_Chives_SeedSapling:
  name: $D_Chives_Seeds
  growTime: 2000
  growRadius: 0.7
  minScale: 0.9
  maxScale: 1.1
  needCultivatedGround: true
  destroyIfCantGrow: false

# Erigeron
D_Erigeron_Sapling:
  name: $D_Erigeron
  growTime: 2000
  growRadius: 0.7
  minScale: 0.9
  maxScale: 1.1
  needCultivatedGround: true
  destroyIfCantGrow: false
D_Erigeron_Seed_Sapling:
  name: $D_Erigeron_Seeds
  growTime: 2000
  growRadius: 0.7
  minScale: 0.9
  maxScale: 1.1
  needCultivatedGround: true
  destroyIfCantGrow: false

# Catharanthus
D_Catharanthus_Sapling:
  name: $D_Catharanthus
  growTime: 2000
  growRadius: 0.7
  minScale: 0.9
  maxScale: 1.1
  needCultivatedGround: true
  destroyIfCantGrow: false
D_Catharanthus_Seed_Sapling:
  name: $D_Catharanthus_Seeds
  growTime: 2000
  growRadius: 0.7
  minScale: 0.9
  maxScale: 1.1
  needCultivatedGround: true
  destroyIfCantGrow: false

